FROM mcr.microsoft.com/dotnet/sdk:3.1 as build
WORKDIR /app
EXPOSE 80
COPY Shared/FreeCourse.Shared/*.csproj Shared/FreeCourse.Shared/
COPY IdentityServer/FreeCouse.IdentityServer/*.csproj IdentityServer/FreeCouse.IdentityServer/ 
RUN dotnet restore  IdentityServer/FreeCouse.IdentityServer/*.csproj
COPY . .
RUN dotnet publish IdentityServer/FreeCouse.IdentityServer/*.csproj -c Release -o out
FROM mcr.microsoft.com/dotnet/aspnet:3.1 as runtime
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT [ "dotnet","FreeCouse.IdentityServer.dll" ]